In [27]:
import torch.nn as nn
import torch

m = nn.Linear(2, 3, bias=False)
input = torch.randn(4, 2)
output = m(input)
print(output.size())

torch.Size([4, 3])


In [28]:
input

tensor([[ 0.8028, -0.3441],
        [ 0.6516,  1.1764],
        [ 0.5118, -0.1745],
        [-0.6976, -0.4048]])

In [29]:
output

tensor([[ 0.2219, -0.0024,  0.6125],
        [ 0.8012,  0.3214,  0.2515],
        [ 0.1606,  0.0084,  0.3830],
        [-0.4931, -0.1542, -0.4135]], grad_fn=<MmBackward>)

In [30]:
m.weight

Parameter containing:
tensor([[ 0.4593,  0.4267],
        [ 0.0922,  0.2221],
        [ 0.6907, -0.1688]], requires_grad=True)

In [31]:
wei = m.weight.detach().numpy() 
#transpose wei
wei = wei.transpose()
wei

array([[ 0.45926604,  0.09221545,  0.6906702 ],
       [ 0.4266947 ,  0.22209534, -0.16878977]], dtype=float32)

In [32]:
import numpy as np
# dot product of input and wei
np.dot(input.numpy(), wei)

array([[ 0.22187601, -0.00238872,  0.6125362 ],
       [ 0.80121595,  0.32135415,  0.2514996 ],
       [ 0.16059345,  0.0084355 ,  0.3829651 ],
       [-0.49310595, -0.15423203, -0.4134844 ]], dtype=float32)